org.gradle.jvmargs=-Xmx4G
org.gradle.configuration-cache=false
org.gradle.daemon=false
modName=ExampleMod
modId=examplemod
modGroup=com.glowingfederal.examplemod
minecraftVersion=1.7.10
forgeVersion=10.13.4.1614
channel=stable
mappingsVersion=12
enableModernJavaSyntax=jabel
enableGenericInjection=true
generateGradleTokenClass=
gradleTokenVersion=
gtnh.modules.gitVersion=false
gtnh.modules.codeStyle=false
gtnh.modules.updater=false
gtnh.settings.dynamicSpotlessVersion=false
gtnh.settings.blowdryerTag=
autoUpdateBuildScript=false
usesMixins=false
usesMavenPublishing=false
includeWellKnownRepositories=false
useModGroupForPublishing=true
noPublishedSources=true
