plugins { id 'java'; id 'xyz.wagyourtail.unimined' version '1.4.1' }
ext.repositoryRoot = file('../..')
ext.minecraftTarget = '1.8.9'
ext.loaderTarget = 'forge'
ext.loaderVersion = '1.8.9-11.15.1.2318-1.8.9'
ext.javaTarget = 8
apply from: '../../build-logic/version.gradle'
apply from: '../../build-logic/shared.gradle'
java.toolchain.languageVersion = JavaLanguageVersion.of(21)
tasks.withType(JavaCompile).configureEach { options.release = 8 }
unimined.minecraft {
    version '1.8.9'
    mappings { searge(); mcp('stable', '22-1.8.9') }
    runs {
        config('client') { javaVersion = JavaVersion.VERSION_1_8 }
        config('server') { javaVersion = JavaVersion.VERSION_1_8 }
    }
    minecraftForge { loader '11.15.1.2318-1.8.9' }
    
}
jar.finalizedBy 'remapJar'
